(define (problem gripper-3) 
(:domain gripper-domain) 
(:objects rooma roomb roomc roomd roome roomf ball1 ball2 ball3 ball4 ball5 ball6 left right up down) 
(:init 
	(room rooma) 
	(room roomb)
	(room roomc)
	(room roomd)
	(room roome)
	(room roomf)
	(ball ball1) 
	(ball ball2)
	(ball ball3)
	(ball ball4)
	(ball ball5)
	(ball ball6)
	(gripper left) 
	(gripper right)
	(gripper up)
	(gripper down)
	(at-robby rooma) 
	(free left) 
	(free right) 
	(free up) 
	(free down) 
	(at ball1 rooma) 
	(at ball2 roomb)
	(at ball3 roomc)
	(at ball4 roomd)
	(at ball5 roome)
	(at ball6 roomf)
)
(:goal (and(at ball1 rooma) (at ball2 rooma) (at ball3 roomb) (at ball4 roomd) (at ball5 roomc) (at ball6 roome))))